import { useMemo, useState } from 'react'
import { Apple, Archive, CalendarDays, ChevronLeft, ChevronRight, CircleUserRound, Clock3, CookingPot, Flame, History, LogOut, PackagePlus, Pencil, Plus, Search, Settings, SlidersHorizontal, Star, Trash2, Utensils, X } from 'lucide-react'
import { CATEGORIES, MEALS, UNIT_LABELS, USERS, calculate, getGoal, prettyDate, shiftDate, todayISO } from './data'
import { useStore } from './useStore'

const round = n => Math.round((Number(n) || 0) * 10) / 10
const sum = rows => rows.reduce((a, e) => ({ calories: a.calories + Number(e.calories || 0), protein: a.protein + Number(e.protein || 0), fat: a.fat + Number(e.fat || 0), carbs: a.carbs + Number(e.carbs || 0) }), { calories: 0, protein: 0, fat: 0, carbs: 0 })

async function sha256(text) {
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text))
  return [...new Uint8Array(buf)].map(b => b.toString(16).padStart(2, '0')).join('')
}

function Login({ onLogin }) {
  const [pin, setPin] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async e => { e.preventDefault(); setBusy(true); const hash = await sha256(pin); const user = USERS.find(u => u.pinHash === hash); setBusy(false); if (!user) { setError('Неверный PIN. Попробуйте ещё раз.'); setPin(''); return } localStorage.setItem('pff-session', user.id); onLogin(user) }
  return <main className="login-shell"><section className="login-card">
    <div className="brand-mark"><Apple size={28} aria-hidden="true" /></div><p className="eyebrow">PANK FAMILY FIT</p><h1>Ваш дневник питания</h1><p className="muted">Спокойно следим за КБЖУ — без лишнего шума.</p>
    <form onSubmit={submit}><label htmlFor="pin">Введите PIN</label><input id="pin" autoFocus inputMode="numeric" autoComplete="one-time-code" maxLength="5" value={pin} onChange={e => { setPin(e.target.value.replace(/\D/g, '')); setError('') }} className="pin-input" placeholder="•••••" aria-invalid={!!error} /><div className="field-error" role="alert">{error}</div><button className="primary wide" disabled={pin.length !== 5 || busy}>{busy ? 'Проверяем…' : 'Войти'}</button></form>
    <p className="privacy">PIN проверяется только в защищённом виде. Устройство запомнит вход.</p>
  </section></main>
}

function MacroCard({ total, goal }) {
  const pct = Math.min(100, goal.calories ? total.calories / goal.calories * 100 : 0)
  const macros = [['Белки', total.protein, goal.protein], ['Жиры', total.fat, goal.fat], ['Углеводы', total.carbs, goal.carbs]]
  return <section className="macro-card" aria-label="Итоги КБЖУ"><div className="calorie-head"><div><span className="section-label">КАЛОРИИ</span><div className="calories">{round(total.calories)} <small>/ {goal.calories}</small></div></div><div className="remaining"><Flame size={17} aria-hidden="true" /><span>Осталось</span><strong>{Math.max(0, round(goal.calories-total.calories))}</strong></div></div><div className="progress"><i style={{ width: `${pct}%` }} /></div><div className="macro-grid">{macros.map(([label,val,max]) => <div key={label}><span>{label}</span><strong>{round(val)} <small>/ {max} г</small></strong></div>)}</div></section>
}

function DayPicker({ date, setDate }) {
  const today = todayISO(); const isToday = date === today
  return <div className="date-row"><button className="icon-button" aria-label="Предыдущий день" onClick={() => setDate(shiftDate(date,-1))}><ChevronLeft /></button><button className="date-title" onClick={() => document.getElementById('date-select')?.showPicker()}><strong>{isToday ? 'Сегодня' : prettyDate(date)}</strong><span>{new Date(`${date}T12:00:00`).toLocaleDateString('ru-RU')}</span><input id="date-select" type="date" value={date} max={today} onChange={e => setDate(e.target.value)} tabIndex="-1" /></button><button className="icon-button" aria-label="Следующий день" disabled={isToday} onClick={() => setDate(shiftDate(date,1))}><ChevronRight /></button></div>
}

function AddFoodModal({ foods, initial, onClose, onSave, onCreate }) {
  const [selected, setSelected] = useState(initial ? foods.find(f => f.id === initial.foodItemId) : null)
  const [query, setQuery] = useState(''); const [amount,setAmount] = useState(initial?.amount || 100); const [unit,setUnit] = useState(initial?.unit || 'g'); const [meal,setMeal] = useState(initial?.mealType || 'breakfast'); const [date,setDate] = useState(initial?.date || todayISO())
  const available = selected ? [{ unit: selected.baseUnit, label: UNIT_LABELS[selected.baseUnit] }, ...(selected.measures || [])] : []
  const calc = selected ? calculate(selected, Number(amount), unit) : null
  const choose = f => { setSelected(f); setUnit(f.baseUnit); setAmount(f.baseAmount) }
  const submit = e => { e.preventDefault(); if (!selected || Number(amount) <= 0) return; onSave({ ...initial, id: initial?.id || crypto.randomUUID(), foodItemId: selected.id, foodName: selected.name, amount: Number(amount), unit, mealType: meal, date, ...calc }) }
  return <div className="scrim" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="sheet" role="dialog" aria-modal="true" aria-labelledby="add-title"><header><div><span className="section-label">ДНЕВНИК</span><h2 id="add-title">{initial ? 'Изменить запись' : 'Добавить еду'}</h2></div><button className="icon-button" aria-label="Закрыть" onClick={onClose}><X /></button></header>
  <form onSubmit={submit}>{!selected ? <><label htmlFor="food-search">Найти продукт</label><div className="search"><Search aria-hidden="true" /><input id="food-search" autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Например, овсянка" /></div><div className="food-results">{foods.filter(f => !f.archived && f.name.toLowerCase().includes(query.toLowerCase())).slice(0,7).map(f => <button type="button" key={f.id} onClick={() => choose(f)}><div className="food-icon"><Utensils aria-hidden="true" /></div><span><strong>{f.name}</strong><small>{f.calories} ккал · Б {f.protein} · Ж {f.fat} · У {f.carbs}</small></span><ChevronRight aria-hidden="true" /></button>)}</div><button type="button" className="secondary wide" onClick={onCreate}><PackagePlus aria-hidden="true" />Создать продукт</button></> : <><button type="button" className="selected-food" onClick={() => setSelected(null)}><span><small>Продукт</small><strong>{selected.name}</strong></span><span>Изменить</span></button><div className="form-grid"><label>Количество<input type="number" min="0.1" step="0.1" value={amount} onChange={e=>setAmount(e.target.value)} /></label><label>Единица<select value={unit} onChange={e=>setUnit(e.target.value)}>{available.map(m=><option key={m.unit} value={m.unit}>{m.label}</option>)}</select></label></div><div className="form-grid"><label>Приём пищи<select value={meal} onChange={e=>setMeal(e.target.value)}>{Object.entries(MEALS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Дата<input type="date" max={todayISO()} value={date} onChange={e=>setDate(e.target.value)} /></label></div><div className="calculation"><span><strong>{round(calc.calories)}</strong> ккал</span><span>Б <strong>{round(calc.protein)}</strong></span><span>Ж <strong>{round(calc.fat)}</strong></span><span>У <strong>{round(calc.carbs)}</strong></span></div><button className="primary wide">{initial ? 'Сохранить изменения' : 'Добавить в дневник'}</button></>}</form></section></div>
}

function ProductModal({ type='product', onClose, onSave }) {
  const [form,setForm] = useState({ name:'', type, category:'Другое', baseUnit:'g', baseAmount:100, calories:'',protein:'',fat:'',carbs:'', measures:[] })
  const field = (key,val) => setForm(f=>({...f,[key]:val}))
  const baseUnit = val => setForm(f=>({...f,baseUnit:val,baseAmount:['piece','portion'].includes(val)?1:100}))
  const addMeasure = () => setForm(f=>({...f,measures:[...f.measures,{unit:'piece',label:'1 штука',amountInBase:1}]}))
  const measureField = (index,key,val) => setForm(f=>({...f,measures:f.measures.map((m,i)=>i===index?{...m,[key]:val}:m)}))
  const submit=e=>{e.preventDefault(); onSave({...form,id:crypto.randomUUID(),baseAmount:Number(form.baseAmount),calories:Number(form.calories),protein:Number(form.protein),fat:Number(form.fat),carbs:Number(form.carbs),favorite:false,archived:false,usageCount:0,measures:form.measures.map(m=>({...m,amountInBase:Number(m.amountInBase)}))})}
  return <div className="scrim"><section className="sheet" role="dialog" aria-modal="true" aria-labelledby="product-title"><header><div><span className="section-label">БАЗА</span><h2 id="product-title">{type==='dish'?'Новое блюдо':'Новый продукт'}</h2></div><button className="icon-button" onClick={onClose} aria-label="Закрыть"><X/></button></header><form onSubmit={submit}><label>Название<input required value={form.name} onChange={e=>field('name',e.target.value)} placeholder="Например, творог 5%" /></label><div className="form-grid"><label>Категория<select value={form.category} onChange={e=>field('category',e.target.value)}>{CATEGORIES.slice(1).map(x=><option key={x}>{x}</option>)}</select></label><label>База<select value={form.baseUnit} onChange={e=>baseUnit(e.target.value)}><option value="g">на 100 г</option><option value="ml">на 100 мл</option><option value="piece">на 1 штуку</option><option value="portion">на 1 порцию</option></select></label></div><p className="form-hint">КБЖУ на выбранную базовую единицу</p><div className="nutrient-inputs">{[['calories','Ккал'],['protein','Белки'],['fat','Жиры'],['carbs','Углеводы']].map(([k,l])=><label key={k}>{l}<input required type="number" min="0" step="0.1" value={form[k]} onChange={e=>field(k,e.target.value)} /></label>)}</div><div className="measure-head"><div><strong>Дополнительные меры</strong><span>Например, 1 стакан = 250 мл</span></div><button type="button" className="small-add" onClick={addMeasure}><Plus/>Добавить</button></div>{form.measures.map((m,i)=><div className="measure-row" key={i}><label>Мера<select value={m.unit} onChange={e=>{const unit=e.target.value;measureField(i,'unit',unit);measureField(i,'label',`1 ${UNIT_LABELS[unit]}`)}}>{Object.entries(UNIT_LABELS).filter(([u])=>u!==form.baseUnit).map(([u,l])=><option key={u} value={u}>{l}</option>)}</select></label><label>В базовых ед.<input required type="number" min="0.1" step="0.1" value={m.amountInBase} onChange={e=>measureField(i,'amountInBase',e.target.value)}/></label><button type="button" aria-label="Удалить меру" onClick={()=>setForm(f=>({...f,measures:f.measures.filter((_,x)=>x!==i)}))}><X/></button></div>)}<button className="primary wide">Сохранить</button></form></section></div>
}

function Today({ viewer, profile, setProfile, data, update, date, setDate }) {
  const [meal,setMeal] = useState('breakfast'); const [modal,setModal]=useState(null); const [creating,setCreating]=useState(false)
  const dayEntries=data.entries.filter(e=>e.userId===profile.id&&e.date===date); const mealEntries=dayEntries.filter(e=>e.mealType===meal); const total=sum(dayEntries); const mealTotal=sum(mealEntries); const goal=getGoal(data.goals,profile.id,date); const noteKey=`${profile.id}:${date}`
  const saveEntry = entry => { update(d=>({...d,entries:[...d.entries.filter(e=>e.id!==entry.id),{...entry,userId:profile.id}],foods:d.foods.map(f=>f.id===entry.foodItemId?{...f,usageCount:(f.usageCount||0)+(!modal?.entry?1:0)}:f)})); setModal(null) }
  const remove=id=> { if (window.confirm('Удалить эту запись из дневника?')) update(d=>({...d,entries:d.entries.filter(e=>e.id!==id)})) }
  const createFood=f=>{update(d=>({...d,foods:[...d.foods,f]}));setCreating(false);setModal({})}
  return <><div className="topbar"><div><p className="eyebrow">PANK FAMILY FIT</p>{viewer.role==='admin'?<div className="profile-switch">{USERS.map(u=><button key={u.id} className={profile.id===u.id?'active':''} onClick={()=>setProfile(u)}>{u.name}</button>)}</div>:<h1>Привет, {viewer.name}</h1>}</div><div className="avatar">{profile.name[0]}</div></div><DayPicker date={date} setDate={setDate}/><MacroCard total={total} goal={goal}/>
  <section className="meal-section"><div className="meal-tabs" role="tablist">{Object.entries(MEALS).map(([k,v])=><button role="tab" aria-selected={meal===k} className={meal===k?'active':''} key={k} onClick={()=>setMeal(k)}>{v}</button>)}</div>
  <div className="meal-list">{mealEntries.length===0?<div className="empty"><div className="empty-icon"><CookingPot aria-hidden="true"/></div><strong>Здесь пока пусто</strong><span>Добавьте первую еду в {MEALS[meal].toLowerCase()}</span></div>:mealEntries.map(e=><article className="meal-row" key={e.id}><div><strong>{e.foodName}</strong><span>{e.amount} {UNIT_LABELS[e.unit] || e.unit} · Б {round(e.protein)} · Ж {round(e.fat)} · У {round(e.carbs)}</span></div><strong>{round(e.calories)} <small>ккал</small></strong><div className="row-actions"><button aria-label={`Изменить ${e.foodName}`} onClick={()=>setModal({entry:e})}><Pencil/></button><button aria-label={`Удалить ${e.foodName}`} onClick={()=>remove(e.id)}><Trash2/></button></div></article>)}</div>
  <div className="meal-total"><span>Итого за приём</span><strong>{round(mealTotal.calories)} ккал</strong></div><button className="primary wide" onClick={()=>setModal({})}><Plus aria-hidden="true"/>Добавить еду</button></section>
  <section className="note-card"><label htmlFor="day-note">Комментарий к дню</label><textarea id="day-note" value={data.notes[noteKey]||''} onChange={e=>update(d=>({...d,notes:{...d.notes,[noteKey]:e.target.value}}))} placeholder="Как прошёл день? Самочувствие, сон, тренировка…"/><span>Сохраняется автоматически</span></section>
  {modal&&<AddFoodModal foods={data.foods} initial={modal.entry?{...modal.entry,foodItemId:modal.entry.foodItemId}:null} onClose={()=>setModal(null)} onSave={saveEntry} onCreate={()=>{setModal(null);setCreating(true)}}/>}{creating&&<ProductModal onClose={()=>setCreating(false)} onSave={createFood}/>}</>
}

function HistoryPage({ profile, data, setDate, goToday }) {
  const dates=[...new Set([...data.entries.filter(e=>e.userId===profile.id).map(e=>e.date),...Object.keys(data.notes).filter(k=>k.startsWith(profile.id+':')).map(k=>k.split(':')[1])])].sort().reverse()
  return <><PageHead eyebrow="ДНЕВНИК" title="История" subtitle={`Все записи · ${profile.name}`}/>{dates.length===0?<div className="page-empty"><History/><h2>История пока пуста</h2><p>Добавленные дни появятся здесь.</p><button className="primary" onClick={goToday}>Перейти к сегодня</button></div>:<div className="history-list">{dates.map(date=>{const totals=sum(data.entries.filter(e=>e.userId===profile.id&&e.date===date)); const goal=getGoal(data.goals,profile.id,date); return <button key={date} onClick={()=>setDate(date)}><CalendarDays/><span><strong>{prettyDate(date)}</strong><small>{round(totals.calories)} из {goal.calories} ккал</small></span><div className="mini-progress"><i style={{width:`${Math.min(100,totals.calories/goal.calories*100)}%`}}/></div><ChevronRight/></button>})}</div>}</>
}

function ProductsPage({data,update}) {
 const [query,setQuery]=useState('');const [category,setCategory]=useState('Все');const [favorites,setFavorites]=useState(false);const [modal,setModal]=useState(null)
 const foods=data.foods.filter(f=>!f.archived&&f.name.toLowerCase().includes(query.toLowerCase())&&(category==='Все'||f.category===category)&&(!favorites||f.favorite)).sort((a,b)=>b.usageCount-a.usageCount)
 const save=f=>{update(d=>({...d,foods:[...d.foods,f]}));setModal(null)}
 return <><PageHead eyebrow="БАЗА" title="Продукты" subtitle={`${data.foods.filter(f=>!f.archived).length} продуктов и блюд`}/><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по продуктам"/></div><div className="filter-row"><select aria-label="Категория" value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><button className={favorites?'filter active':'filter'} aria-pressed={favorites} onClick={()=>setFavorites(!favorites)}><Star/>Любимые</button></div><div className="product-actions"><button className="primary" onClick={()=>setModal('product')}><Plus/>Продукт</button><button className="secondary" onClick={()=>setModal('dish')}><Plus/>Блюдо</button></div><div className="product-list">{foods.map(f=><article key={f.id}><button className="star-button" aria-label={f.favorite?'Убрать из любимых':'Добавить в любимые'} onClick={()=>update(d=>({...d,foods:d.foods.map(x=>x.id===f.id?{...x,favorite:!x.favorite}:x)}))}><Star className={f.favorite?'filled':''}/></button><div><strong>{f.name}</strong><span>{f.category} · {f.type==='dish'?'Блюдо':'Продукт'}</span><small>{f.calories} ккал · Б {f.protein} · Ж {f.fat} · У {f.carbs}</small></div><button className="archive-button" aria-label={`Архивировать ${f.name}`} onClick={()=>update(d=>({...d,foods:d.foods.map(x=>x.id===f.id?{...x,archived:true}:x)}))}><Archive/></button></article>)}</div>{modal&&<ProductModal type={modal} onClose={()=>setModal(null)} onSave={save}/>}</>
}

function SettingsPage({viewer,data,update,onLogout}) {
 const [profileId,setProfileId]=useState('danya'); const current=USERS.find(u=>u.id===profileId); const latest=getGoal(data.goals,profileId,todayISO()); const [form,setForm]=useState({...latest,startDate:todayISO()});
 const select=id=>{setProfileId(id);const g=getGoal(data.goals,id,todayISO());setForm({...g,startDate:todayISO()})}; const save=e=>{e.preventDefault();update(d=>({...d,goals:[...d.goals,{...form,id:crypto.randomUUID(),userId:profileId,calories:Number(form.calories),protein:Number(form.protein),fat:Number(form.fat),carbs:Number(form.carbs)}]}))}
 return <><PageHead eyebrow="ПРОФИЛЬ" title="Настройки" subtitle={`Вы вошли как ${viewer.name}`}/>{viewer.role==='admin'&&<section className="settings-card"><div className="card-title"><div><span className="section-label">ЦЕЛИ КБЖУ</span><h2>Новая цель</h2></div><SlidersHorizontal/></div><div className="profile-switch compact">{USERS.map(u=><button key={u.id} className={profileId===u.id?'active':''} onClick={()=>select(u.id)}>{u.name}</button>)}</div><form onSubmit={save}><label>Применить с даты<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><div className="nutrient-inputs">{[['calories','Ккал'],['protein','Белки'],['fat','Жиры'],['carbs','Углеводы']].map(([k,l])=><label key={k}>{l}<input type="number" min="0" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="primary wide">Сохранить новую цель</button></form><p className="form-hint">Старые дни сохранят прежние цели.</p></section>}<section className="settings-card"><div className="card-title"><div><span className="section-label">УСТРОЙСТВО</span><h2>Сеанс</h2></div><CircleUserRound/></div><button className="danger wide" onClick={onLogout}><LogOut/>Выйти на этом устройстве</button></section></>
}

function PageHead({eyebrow,title,subtitle}) { return <header className="page-head"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{subtitle}</p></header> }

function BottomNav({viewer,page,setPage}) { const links=[['today',Clock3,'Сегодня'],['history',History,'История'],...(viewer.role==='admin'?[['products',Apple,'Продукты']]:[]),['settings',Settings,'Настройки']]; return <nav className="bottom-nav" aria-label="Основная навигация">{links.map(([key,Icon,label])=><button key={key} className={page===key?'active':''} aria-current={page===key?'page':undefined} onClick={()=>setPage(key)}><Icon aria-hidden="true"/><span>{label}</span></button>)}</nav> }

export default function App() {
 const [viewer,setViewer]=useState(()=>USERS.find(u=>u.id===localStorage.getItem('pff-session'))||null); const [profile,setProfile]=useState(viewer||USERS[0]); const [page,setPage]=useState('today'); const [date,setDate]=useState(todayISO()); const {data,update}=useStore()
 if(!viewer)return <Login onLogin={u=>{setViewer(u);setProfile(u)}}/>
 const gotoDate=d=>{setDate(d);setPage('today')}; const logout=()=>{localStorage.removeItem('pff-session');setPage('today');setDate(todayISO());setViewer(null)}
 return <div className="desktop-bg"><main className="app-shell"><div className="scroll-area">{page==='today'&&<Today viewer={viewer} profile={profile} setProfile={setProfile} data={data} update={update} date={date} setDate={setDate}/>} {page==='history'&&<HistoryPage profile={profile} data={data} setDate={gotoDate} goToday={()=>gotoDate(todayISO())}/>} {page==='products'&&viewer.role==='admin'&&<ProductsPage data={data} update={update}/>} {page==='settings'&&<SettingsPage viewer={viewer} data={data} update={update} onLogout={logout}/>}</div><BottomNav viewer={viewer} page={page} setPage={setPage}/></main></div>
}
